image: maven:3.6.0
stages:
    - build

build:
    stage: build
    script: mvn -X clean install
    artifacts:
        paths:
            - build/com.opcoach.genmodeladdon.repository/target/com.opcoach.genmodeladdon.repository-2.2.0-SNAPSHOT.zip

